# Generated by Django 3.2.13 on 2022-07-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0003_remove_group_nature_of_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('provide_banking_details', models.CharField(max_length=225)),
                ('pan_no', models.CharField(max_length=225)),
            ],
        ),
    ]
