# Generated by Django 3.2.13 on 2022-07-08 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0004_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies'),
        ),
    ]
