# Generated by Django 3.2.13 on 2022-07-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0005_ledger_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger_Mailing_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Null', max_length=225)),
                ('address', models.CharField(blank=True, default='Null', max_length=225)),
                ('state', models.CharField(blank=True, default='Null', max_length=225)),
                ('country', models.CharField(blank=True, default='Null', max_length=225)),
                ('pincode', models.CharField(blank=True, default='Null', max_length=225)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.ledger')),
            ],
        ),
    ]
