# Generated by Django 3.2.13 on 2022-07-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0006_ledger_mailing_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger_mailing_details',
            old_name='name',
            new_name='mailingname',
        ),
    ]
