# Generated by Django 3.2.13 on 2022-07-08 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0007_rename_name_ledger_mailing_details_mailingname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger_Banking_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_limit', models.CharField(blank=True, default='Null', max_length=225)),
                ('holder_name', models.CharField(blank=True, default='Null', max_length=225)),
                ('acc_no', models.CharField(blank=True, default='Null', max_length=225)),
                ('ifsc', models.CharField(blank=True, default='Null', max_length=225)),
                ('swift_code', models.CharField(blank=True, default='Null', max_length=225)),
                ('bank_name', models.CharField(blank=True, default='Null', max_length=225)),
                ('branch', models.CharField(blank=True, default='Null', max_length=225)),
                ('set_cheque', models.CharField(blank=True, default='Null', max_length=225)),
                ('ch_printing', models.CharField(blank=True, default='Null', max_length=225)),
                ('ch_config', models.CharField(blank=True, default='Null', max_length=225)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.ledger')),
            ],
        ),
    ]
