# Generated by Django 3.2.13 on 2022-07-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyapp', '0008_ledger_banking_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_banking_details',
            name='acc_no',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_banking_details',
            name='bank_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_banking_details',
            name='branch',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_banking_details',
            name='ch_config',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_banking_details',
            name='ch_printing',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_banking_details',
            name='holder_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_banking_details',
            name='ifsc',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_banking_details',
            name='od_limit',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_banking_details',
            name='set_cheque',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_banking_details',
            name='swift_code',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_mailing_details',
            name='address',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_mailing_details',
            name='country',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_mailing_details',
            name='mailingname',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_mailing_details',
            name='pincode',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ledger_mailing_details',
            name='state',
            field=models.CharField(max_length=225),
        ),
        migrations.CreateModel(
            name='Ledger_Asset_Statutory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessable_calculation', models.CharField(max_length=225)),
                ('appropriate_to', models.CharField(max_length=225)),
                ('gst_applicable', models.CharField(max_length=225)),
                ('set_alter_GST', models.CharField(max_length=225)),
                ('type_of_supply', models.CharField(max_length=225)),
                ('method_of_calc', models.CharField(max_length=225)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_Asset_Rounding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounding_method', models.CharField(max_length=225)),
                ('round_limit', models.CharField(max_length=225)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.companies')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tallyapp.ledger')),
            ],
        ),
    ]
